Use rpm/precheckin.sh to generate spec files.
Follows the specification as laid out by Thomas Perl in
https://github.com/MeeGoIntegration/boss-launcher-webhook/issues/5

diff --git a/src/service/tar_git b/src/service/tar_git
--- a/src/service/tar_git
+++ b/src/service/tar_git
@@ -196,6 +196,18 @@ sanitise_params () {
 
 }
 
+generate_spec_files () {
+
+    [[ -f "rpm/precheckin.sh" ]] || return 0
+
+    echo "Generating spec files from rpm/precheckin.sh"
+    pushd rpm >/dev/null
+    rm -f *.spec
+    sh precheckin.sh || error "Could not generate .spec files with precheckin.sh"
+    popd >/dev/null
+
+}
+
 find_spec_file () {
 
   [[ -d "$1" ]] || error "no packaging in this git clone"
@@ -1091,6 +1103,7 @@ main () {
     return
   fi
   pushd "$CLONE_NAME" >/dev/null
+  generate_spec_files
   # check for default manifest file
   if test -f default.xml; then
     run_android_repo_service
